/*
 * ADC_CONFIG.h
 *
 *  Created on: Oct 9, 2021
 *      Author: LENOVO
 */

#ifndef ADC_ADC_CONFIG_H_
#define ADC_ADC_CONFIG_H_

/*
 * please select the refrerance voltage
		 AREF_INTERNAL_VREF_TURNED_OFF
  	  	 AVCC_WITH_EXTERNAL_CAPACITOR_AT_AREF_PIN
 	 	 INTERNAL_256V_VOLTAGE_REFERENCE_WITH_EXTERNAL_CAPACITOR_AT_AREF_PIN
 */


#define ADC_REFERANCE_VOLTAGE     AVCC_WITH_EXTERNAL_CAPACITOR_AT_AREF_PIN



/*
 * PLEASE CHOSE DATA ADJUSTMENT
  LEFT
  RIGHT
 */

#define ADC_DATA_ADJUSTMENT   			RIGHT

/*
 * PLEASE CHOSE AUT_TRIGGER
  ENABLE
  DISABLE
 */

#define ADC_AUT_TRIGGER       DISABLE



#if ADC_AUT_TRIGGER ==ENABLE
/*
 * PLEASE CHOSE THE AUTO TRIGGERING SOURCE
  FREE_RUNNING_MODE
  Analog_Comparator
  External_Interrupt_Request_0
  TIMER_COUNTER0_COMPARE_MATCH
  TIMER_COUNTER0_OVERFLOW
  TIMER_COUNTER_COMPARE_MATCH_B
  TIMER_COUNTER1_OVERFLOW
  TIMER_COUNTER1_CAPTURE_EVENT
 *
 */
#define  AUTO_TRIGGERING_SOURCE 		FREE_RUNNING_MODE

#endif

/*
 * PLEASE CHOSE ADC INTERRUPT
  ENABLE
  DISABLE
 */
#define ADC_INTERRUPT 		DISABLE

/*
 * PLEASE CHOSE PRESCALER
 DIV_BY_2
 DIV_BY_4
 DIV_BY_8
 DIV_BY_16
 DIV_BY_32
 DIV_BY_64
 DIV_BY_128
 */


# define ADC_PRESCALER_VALUE  DIV_BY_64


#endif /* ADC_ADC_CONFIG_H_ */
